# Generated by Django 5.0.6 on 2024-05-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True, null=True)),
                ("slug", models.CharField(max_length=100)),
                ("metaDescription", models.TextField(blank=True, null=True)),
                ("postedAt", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
